[package]
name = "lxi-client"
version = "0.1.0"
authors = ["gustavp"]
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]