license = "GPL-3.0-or-later"

[workspace]
members = [
    "visa",
    "device",
    "hislip",
    "raw",
    "telnet",
    "vxi11"
]

[workspace.package]
version = "0.1.0"
authors = ["Gustav Palmqvist <gustavp@gpa-robotics.com>"]
repository = "https://github.com/Atmelfan/lxi-rs"
edition = "2021"