authors = ["Gustav Palmqvist <gustavp@gpa-robotics.com>"]
license = "GPL-3.0-or-later"

[workspace]
members = [
    "client",
    "device",
    "hislip",
    "socket",
    "vxi11",
    "app",
    "web"
]

[workspace.metadata.release]
pre-release-hook = ['./pre-release-hook.sh']
