[tls]
cert = "end.cert"
key = "end.rsa"

[hislip]
enable = true
#port = 4880

[vxi11]
enable = true
core-port = 5000
async-port = 5001

[socket]
enable = true
#port = 5025

[telnet]
enable = true
#port = 5024