[package]
name = "lxi-device"
version = "0.1.0"
authors = ["gustavp"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# lock_api = "0.4" # TODO: No-std support
async-std = "1.10.0"
futures = "0.3.13"