[package]
name = "lxi-device"
version = "0.1.0"
authors = ["Gustav Palmqvist <gustavp@gpa-robotics.com>"]
edition = "2021"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = {version = "0.3", features = ["alloc"]}
spin = {version = "0.9.3", default-features = false, features = ["spin_mutex", "mutex"]}
log = "0.4.17"

[dev-dependencies]

[features]
default = []
std = []