#[allow(non_camel_case_types)]
#[allow(non_snake_case)]
mod xdr {
    //! Autogenerated by xdrgen
    use xdr_codec;

    #[allow(dead_code)]
    include!(concat!(env!("OUT_DIR"), "/vxi11_xdr.rs"));
}
