[package]
name = "hislip"
version = "0.1.0"
authors = ["Atmelfan <gustavp@gpa-robotics.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.9.0"
futures = "0.3.13"
#async-tls = "0.11.0"
rustls = "0.19.0"
log = "0.4.4"
byteorder = "1.3"
bitfield = "0.13.2"

[dev-dependencies]
structopt = "0.3.21"
env_logger = "0.8.3"
