[package]
name = "lxi-hislip"
version = "0.1.0"
authors = ["Atmelfan <gustavp@gpa-robotics.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = {version = "1.11", features = ["attributes"]}
futures = "0.3"
async-tls = "0.11"
byteorder = "1.3"
bitfield = "0.13"

# Logging
kv-log-macro = "1.0.7"
log = { version = "0.4.17", features = ["kv_unstable_std"] }

[dependencies.lxi-device]
path = "../device"

[dev-dependencies]
env_logger = "0.9.0"
clap = { version = "3.1.12", features = ["derive"] }
